### ISSUE TITLE
Renovate latest python version

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-python#30]

**Comment by viceice** [comment]
? What to do here?

**Comment by rarkins** [comment]
We are on latest 3.7.5 according to builder.json. Shouldn't Renovate update automatically to 3.8.x ?

**Comment by viceice** [comment]
it builds [3.8.x](https://hub.docker.com/r/renovate/python/tags?page=1&name=3.8) The latest it only to pin the `latest` docker tag for now.

Should we raise it to a later version?

**Comment by rarkins** [comment]
Sorry, we can wait until after the PR in the main repo is merged. Working on that now

**Comment by viceice** [comment]
you need to fix the eslint issue on master branch of renovate 😢
