### ISSUE TITLE
Update renovate/python on dockerhub to 3.9.4

### ISSUE THREAD

**Issue by pheanex** [renovatebot/docker-python#64]
**What would you like Renovate to be able to do?**

Run renovate with the latest released [Python version of 3.9,4](https://www.python.org/downloads/release/python-394/).
At the moment the latest version of[ renovate/python on dockerhub is 3.9.3](https://hub.docker.com/r/renovate/python/tags?page=1&ordering=last_updated).
Renovate fails if the project it checks depends on 3.9.4 with:
```
Command failed: docker run --rm --name=renovate_python --label=renovate_child ... -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/pipenv":"/tmp/renovate-cache/others/pipenv" -e PIPENV_CACHE_DIR -w ... docker.io/renovate/python:latest bash -l -c "pip install --user pipenv && pipenv lock"
Warning: Python 3.9.4 was not found on your system...
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
```

**Comment by rarkins** [comment]
This should normally not require any manual intervention but we are switching over our build process and I think we missed a reference. I think this will be automatically resolved after this commit: https://github.com/renovatebot/docker-python/commit/1f68169bc93d5ce2a5df640e9c9ca9fec17a9156

**Comment by rarkins** [comment]
Now done: https://hub.docker.com/layers/renovate/python/3.9.4/images/sha256-1ac43511c807ed769dbac7f5172679011e68c35ec532df225b7d5696ef2f21a4?context=explore

Should not require any manual intervention in future.

**Comment by pheanex** [comment]
Thank you very much @rarkins :smiley:

**Comment by viceice** [comment]
I missed that, sorry. Hopefully the transition can be finished by next week.
